######################################################################
# Automatically generated by qmake (3.0) lun. d�c. 23 17:05:01 2013
######################################################################

TEMPLATE = app
TARGET = QtMars
INCLUDEPATH += .

# Input
HEADERS += opengl_window.h triangle_window.h
FORMS +=
SOURCES += main.cpp opengl_window.cpp triangle_window.cpp
QT += widgets
